sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t biggnou/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true biggnou/docker-react npm run test
